name: Deploy pages site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: DeterminateSystems/magic-nix-cache-action@v7
      with:
        diagnostic-endpoint: "" # Disable telemetry

    - name: Build site
      run: nix build .#site

    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: result
